language: python
python:
  - "2.7"
  - "pypy"
env:
  - SMMAP=smmap
  - SMMAP=git+https://github.com/Byron/smmap.git#egg=smmap
matrix:
  allow_failures:
    - python: pypy
services:
  - elasticsearch
install:
  - pip install $SMMAP
  - pip install -r requirements.txt --use-wheel
  - pip install -r requirements-dev.txt --use-wheel
  - pip install -e . --use-wheel
  - pip install coveralls --use-wheel
script:
  - py.test elasticgit
  - cd docs && make doctest && cd -
after_success:
  - coveralls
